### PR TITLE
MAINT: Apply black formatter, isort, remove trailing spaces

### PR DESCRIPTION
**Pull request by MartinThoma**
MAINT: Move meta-data from setup.py to setup.cfg
TST: Add unittest example (with pytest)
MAINT: Fix many mypy issues (but not all)
MAINT: Fix some Flake8 issues (but not all)

### CODE REVIEW

**Comment by MartinThoma** [comment]
I highly recommend to install pre-commit: https://pre-commit.com/

    pip install pre-commit

Once you have it on your system, you can go in this repository (this branch) and execute "pre-commit install". The effect is, that every time you execute "git commit" it will run all the checks I defined in the pre-commit file. This allows you to keep a high quality.

Additionally, I recommend installing pytest and pytest-cov and pytest-flake:

    pip install pytest pytest-cov pytest-flake8

You can then run 

    pytest

within the git repository. At the moment, not too much is tested. Adding more would be valuable.

**Comment by MartinThoma** [comment]
There were also a couple of dependencies missing. I've added them.

I could not find `cotools`. Is it maybe a file you forgot to commit?

**Comment by josephsdavid** [comment]
Hi Martin! Cotools is installed by `pip install cord-19-tools`, I have terrible naming conventions

**Comment by josephsdavid** [comment]
A lot of the stuff out of comodels is just scratch work too, I’ll get that cleaned up :)

**Comment by josephsdavid** [comment]
Thanks a ton!!!

**Comment by MartinThoma** [comment]
No problem, I love to support :-) 

As the name is different on GitHub and on PyPI, you might want to add

```
[![PyPI version](https://badge.fury.io/py/covid-modeling.svg)](https://badge.fury.io/py/covid-modeling)
```

to the top of the README.

**Comment by josephsdavid** [comment]
My hero :)

**Pull request merged**
